version: '3.8'

services:
  monitor:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./incidents.db:/app/incidents.db
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "5000:5000"
    depends_on:
      - monitor